"""add zipcode

Revision ID: e76a1a967a33
Revises: 834b1a697901
Create Date: 2018-05-08 14:26:36.445333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76a1a967a33'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zipcode', sa.String(length=65), nullable=True))
    op.create_index(op.f('ix_user_zipcode'), 'user', ['zipcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_zipcode'), table_name='user')
    op.drop_column('user', 'zipcode')
    # ### end Alembic commands ###
